[package]
name = "fkl_codegen_java"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genco = "0.17.2"
anyhow = "1.0.31"

fkl-parser = { path = "../fkl_parser" }
