[package]
name = "fkl-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.3.1"
pest_derive = "2.3.1"

indexmap = "1.9.1"

serde = { version = "1", features = ["derive"] }
