name: CD
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master

      - run: npm install --legacy-peer-deps

      - run: npx nx workspace-lint

      - run: npx nx run-many --target=lint --all

      - run: npm run build:all

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_KEY }}
          repository-name: feakin/online
          folder: packages/render/dist

      - name: Build
        run: cargo build --release --manifest-path=crates/server/Cargo.toml

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "feakin"
          heroku_email: "gmszone@qq.com"
          buildpack: "https://github.com/emk/heroku-buildpack-rust.git"
