name: CI
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: npm install --legacy-peer-deps

      - run: npx nx workspace-lint

      - run: npx nx run-many --target=lint --all

      - run: npm run build:all

      - run: npm run test:all

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_KEY }}
          repository-name: feakin/online
          folder: packages/render/dist
