name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm install -g concurrently

      - run: npm install --legacy-peer-deps

      - run: npm run test:all

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
